/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Feedback {
  'id' : string,
  'createdAt' : Time,
  'reviewText' : string,
  'nurseId' : string,
  'patientName' : string,
  'mediaUrls' : Array<ExternalBlob>,
  'rating' : bigint,
}
export interface Nurse {
  'id' : string,
  'bio' : string,
  'latitude' : [] | [number],
  'name' : string,
  'profilePhoto' : [] | [ExternalBlob],
  'isAvailable' : boolean,
  'registrationNumber' : string,
  'district' : string,
  'experience' : bigint,
  'longitude' : [] | [number],
  'village' : string,
  'mandal' : string,
  'phone' : string,
  'pincode' : bigint,
}
export interface ServiceProof {
  'id' : string,
  'photoUrls' : Array<ExternalBlob>,
  'createdAt' : Time,
  'description' : string,
  'nurseId' : string,
  'videoUrl' : [] | [ExternalBlob],
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addNurse' : ActorMethod<[Nurse], undefined>,
  'addServiceProof' : ActorMethod<[ServiceProof], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteNurse' : ActorMethod<[string], undefined>,
  'deleteServiceProof' : ActorMethod<[string], undefined>,
  'filterByPincode' : ActorMethod<[bigint], Array<Nurse>>,
  'findNurseByCredentials' : ActorMethod<[string, string], [] | [Nurse]>,
  'getAggregateRating' : ActorMethod<[string], [] | [number]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getNurse' : ActorMethod<[string], [] | [Nurse]>,
  'getNurseFeedback' : ActorMethod<[string], Array<Feedback>>,
  'getNurseServiceProofs' : ActorMethod<[string], Array<ServiceProof>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllNurses' : ActorMethod<[], Array<Nurse>>,
  'listAllServiceProofs' : ActorMethod<[], Array<ServiceProof>>,
  'registerNurse' : ActorMethod<[Nurse], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setNurseAvailability' : ActorMethod<[string, string, boolean], undefined>,
  'submitFeedback' : ActorMethod<[Feedback], undefined>,
  'updateNurse' : ActorMethod<[Nurse], undefined>,
  'updateNurseLocation' : ActorMethod<
    [string, string, number, number],
    undefined
  >,
  'updateServiceProof' : ActorMethod<[ServiceProof], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];