/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Nurse = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'profilePhoto' : IDL.Opt(ExternalBlob),
  'isAvailable' : IDL.Bool,
  'registrationNumber' : IDL.Text,
  'district' : IDL.Text,
  'experience' : IDL.Nat,
  'village' : IDL.Text,
  'mandal' : IDL.Text,
  'phone' : IDL.Text,
  'pincode' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const Time = IDL.Int;
export const Feedback = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : Time,
  'reviewText' : IDL.Text,
  'nurseId' : IDL.Text,
  'patientName' : IDL.Text,
  'mediaUrls' : IDL.Vec(ExternalBlob),
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addNurse' : IDL.Func([Nurse], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteNurse' : IDL.Func([IDL.Text], [], []),
  'filterByPincode' : IDL.Func([IDL.Nat], [IDL.Vec(Nurse)], ['query']),
  'getAggregateRating' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Float64)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getNurse' : IDL.Func([IDL.Text], [IDL.Opt(Nurse)], ['query']),
  'getNurseFeedback' : IDL.Func([IDL.Text], [IDL.Vec(Feedback)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllNurses' : IDL.Func([], [IDL.Vec(Nurse)], ['query']),
  'registerNurse' : IDL.Func([Nurse], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitFeedback' : IDL.Func([Feedback], [], []),
  'updateNurse' : IDL.Func([Nurse], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Nurse = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'profilePhoto' : IDL.Opt(ExternalBlob),
    'isAvailable' : IDL.Bool,
    'registrationNumber' : IDL.Text,
    'district' : IDL.Text,
    'experience' : IDL.Nat,
    'village' : IDL.Text,
    'mandal' : IDL.Text,
    'phone' : IDL.Text,
    'pincode' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const Time = IDL.Int;
  const Feedback = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : Time,
    'reviewText' : IDL.Text,
    'nurseId' : IDL.Text,
    'patientName' : IDL.Text,
    'mediaUrls' : IDL.Vec(ExternalBlob),
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addNurse' : IDL.Func([Nurse], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteNurse' : IDL.Func([IDL.Text], [], []),
    'filterByPincode' : IDL.Func([IDL.Nat], [IDL.Vec(Nurse)], ['query']),
    'getAggregateRating' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Float64)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getNurse' : IDL.Func([IDL.Text], [IDL.Opt(Nurse)], ['query']),
    'getNurseFeedback' : IDL.Func([IDL.Text], [IDL.Vec(Feedback)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllNurses' : IDL.Func([], [IDL.Vec(Nurse)], ['query']),
    'registerNurse' : IDL.Func([Nurse], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitFeedback' : IDL.Func([Feedback], [], []),
    'updateNurse' : IDL.Func([Nurse], [], []),
  });
};

export const init = ({ IDL }) => { return []; };