/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Feedback {
    id: string;
    createdAt: Time;
    reviewText: string;
    nurseId: string;
    patientName: string;
    mediaUrls: Array<ExternalBlob>;
    rating: bigint;
}
export interface ServiceProof {
    id: string;
    photoUrls: Array<ExternalBlob>;
    createdAt: Time;
    description: string;
    nurseId: string;
    videoUrl?: ExternalBlob;
}
export interface Nurse {
    id: string;
    bio: string;
    latitude?: number;
    name: string;
    profilePhoto?: ExternalBlob;
    isAvailable: boolean;
    registrationNumber: string;
    district: string;
    experience: bigint;
    longitude?: number;
    village: string;
    mandal: string;
    phone: string;
    pincode: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface UserProfile {
    name: string;
    email?: string;
    phone?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addNurse(nurse: Nurse): Promise<void>;
    addServiceProof(proof: ServiceProof): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteNurse(nurseId: string): Promise<void>;
    deleteServiceProof(proofId: string): Promise<void>;
    filterByPincode(pincode: bigint): Promise<Array<Nurse>>;
    findNurseByCredentials(registrationNumber: string, phone: string): Promise<Nurse | null>;
    getAggregateRating(nurseId: string): Promise<number | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getNurse(id: string): Promise<Nurse | null>;
    getNurseFeedback(nurseId: string): Promise<Array<Feedback>>;
    getNurseServiceProofs(nurseId: string): Promise<Array<ServiceProof>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listAllNurses(): Promise<Array<Nurse>>;
    listAllServiceProofs(): Promise<Array<ServiceProof>>;
    registerNurse(nurse: Nurse): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setNurseAvailability(registrationNumber: string, phone: string, isAvailable: boolean): Promise<void>;
    submitFeedback(feedback: Feedback): Promise<void>;
    updateNurse(nurse: Nurse): Promise<void>;
    updateNurseLocation(registrationNumber: string, phone: string, latitude: number, longitude: number): Promise<void>;
    updateServiceProof(proof: ServiceProof): Promise<void>;
}
import type { ExternalBlob as _ExternalBlob, Feedback as _Feedback, Nurse as _Nurse, ServiceProof as _ServiceProof, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addNurse(arg0: Nurse): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNurse(await to_candid_Nurse_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNurse(await to_candid_Nurse_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addServiceProof(arg0: ServiceProof): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addServiceProof(await to_candid_ServiceProof_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addServiceProof(await to_candid_ServiceProof_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteNurse(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNurse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNurse(arg0);
            return result;
        }
    }
    async deleteServiceProof(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteServiceProof(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteServiceProof(arg0);
            return result;
        }
    }
    async filterByPincode(arg0: bigint): Promise<Array<Nurse>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterByPincode(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterByPincode(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async findNurseByCredentials(arg0: string, arg1: string): Promise<Nurse | null> {
        if (this.processError) {
            try {
                const result = await this.actor.findNurseByCredentials(arg0, arg1);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findNurseByCredentials(arg0, arg1);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAggregateRating(arg0: string): Promise<number | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAggregateRating(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAggregateRating(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNurse(arg0: string): Promise<Nurse | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNurse(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNurse(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNurseFeedback(arg0: string): Promise<Array<Feedback>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNurseFeedback(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNurseFeedback(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNurseServiceProofs(arg0: string): Promise<Array<ServiceProof>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNurseServiceProofs(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNurseServiceProofs(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllNurses(): Promise<Array<Nurse>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllNurses();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllNurses();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllServiceProofs(): Promise<Array<ServiceProof>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllServiceProofs();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllServiceProofs();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerNurse(arg0: Nurse): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerNurse(await to_candid_Nurse_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerNurse(await to_candid_Nurse_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setNurseAvailability(arg0: string, arg1: string, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setNurseAvailability(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setNurseAvailability(arg0, arg1, arg2);
            return result;
        }
    }
    async submitFeedback(arg0: Feedback): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitFeedback(await to_candid_Feedback_n38(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitFeedback(await to_candid_Feedback_n38(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateNurse(arg0: Nurse): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNurse(await to_candid_Nurse_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNurse(await to_candid_Nurse_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateNurseLocation(arg0: string, arg1: string, arg2: number, arg3: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNurseLocation(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNurseLocation(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateServiceProof(arg0: ServiceProof): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateServiceProof(await to_candid_ServiceProof_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateServiceProof(await to_candid_ServiceProof_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_Feedback_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Feedback): Promise<Feedback> {
    return await from_candid_record_n31(_uploadFile, _downloadFile, value);
}
async function from_candid_Nurse_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Nurse): Promise<Nurse> {
    return await from_candid_record_n18(_uploadFile, _downloadFile, value);
}
async function from_candid_ServiceProof_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceProof): Promise<ServiceProof> {
    return await from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n21(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Nurse]): Promise<Nurse | null> {
    return value.length === 0 ? null : await from_candid_Nurse_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    bio: string;
    latitude: [] | [number];
    name: string;
    profilePhoto: [] | [_ExternalBlob];
    isAvailable: boolean;
    registrationNumber: string;
    district: string;
    experience: bigint;
    longitude: [] | [number];
    village: string;
    mandal: string;
    phone: string;
    pincode: bigint;
}): Promise<{
    id: string;
    bio: string;
    latitude?: number;
    name: string;
    profilePhoto?: ExternalBlob;
    isAvailable: boolean;
    registrationNumber: string;
    district: string;
    experience: bigint;
    longitude?: number;
    village: string;
    mandal: string;
    phone: string;
    pincode: bigint;
}> {
    return {
        id: value.id,
        bio: value.bio,
        latitude: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.latitude)),
        name: value.name,
        profilePhoto: record_opt_to_undefined(await from_candid_opt_n20(_uploadFile, _downloadFile, value.profilePhoto)),
        isAvailable: value.isAvailable,
        registrationNumber: value.registrationNumber,
        district: value.district,
        experience: value.experience,
        longitude: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.longitude)),
        village: value.village,
        mandal: value.mandal,
        phone: value.phone,
        pincode: value.pincode
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
    phone: [] | [string];
}): {
    name: string;
    email?: string;
    phone?: string;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.email)),
        phone: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.phone))
    };
}
async function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    createdAt: _Time;
    reviewText: string;
    nurseId: string;
    patientName: string;
    mediaUrls: Array<_ExternalBlob>;
    rating: bigint;
}): Promise<{
    id: string;
    createdAt: Time;
    reviewText: string;
    nurseId: string;
    patientName: string;
    mediaUrls: Array<ExternalBlob>;
    rating: bigint;
}> {
    return {
        id: value.id,
        createdAt: value.createdAt,
        reviewText: value.reviewText,
        nurseId: value.nurseId,
        patientName: value.patientName,
        mediaUrls: await from_candid_vec_n32(_uploadFile, _downloadFile, value.mediaUrls),
        rating: value.rating
    };
}
async function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    photoUrls: Array<_ExternalBlob>;
    createdAt: _Time;
    description: string;
    nurseId: string;
    videoUrl: [] | [_ExternalBlob];
}): Promise<{
    id: string;
    photoUrls: Array<ExternalBlob>;
    createdAt: Time;
    description: string;
    nurseId: string;
    videoUrl?: ExternalBlob;
}> {
    return {
        id: value.id,
        photoUrls: await from_candid_vec_n32(_uploadFile, _downloadFile, value.photoUrls),
        createdAt: value.createdAt,
        description: value.description,
        nurseId: value.nurseId,
        videoUrl: record_opt_to_undefined(await from_candid_opt_n20(_uploadFile, _downloadFile, value.videoUrl))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Nurse>): Promise<Array<Nurse>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Nurse_n17(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Feedback>): Promise<Array<Feedback>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Feedback_n30(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n21(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ServiceProof>): Promise<Array<ServiceProof>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ServiceProof_n34(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_Feedback_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Feedback): Promise<_Feedback> {
    return await to_candid_record_n39(_uploadFile, _downloadFile, value);
}
async function to_candid_Nurse_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Nurse): Promise<_Nurse> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_ServiceProof_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceProof): Promise<_ServiceProof> {
    return await to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    photoUrls: Array<ExternalBlob>;
    createdAt: Time;
    description: string;
    nurseId: string;
    videoUrl?: ExternalBlob;
}): Promise<{
    id: string;
    photoUrls: Array<_ExternalBlob>;
    createdAt: _Time;
    description: string;
    nurseId: string;
    videoUrl: [] | [_ExternalBlob];
}> {
    return {
        id: value.id,
        photoUrls: await to_candid_vec_n13(_uploadFile, _downloadFile, value.photoUrls),
        createdAt: value.createdAt,
        description: value.description,
        nurseId: value.nurseId,
        videoUrl: value.videoUrl ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.videoUrl)) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
    phone?: string;
}): {
    name: string;
    email: [] | [string];
    phone: [] | [string];
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
async function to_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    createdAt: Time;
    reviewText: string;
    nurseId: string;
    patientName: string;
    mediaUrls: Array<ExternalBlob>;
    rating: bigint;
}): Promise<{
    id: string;
    createdAt: _Time;
    reviewText: string;
    nurseId: string;
    patientName: string;
    mediaUrls: Array<_ExternalBlob>;
    rating: bigint;
}> {
    return {
        id: value.id,
        createdAt: value.createdAt,
        reviewText: value.reviewText,
        nurseId: value.nurseId,
        patientName: value.patientName,
        mediaUrls: await to_candid_vec_n13(_uploadFile, _downloadFile, value.mediaUrls),
        rating: value.rating
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    bio: string;
    latitude?: number;
    name: string;
    profilePhoto?: ExternalBlob;
    isAvailable: boolean;
    registrationNumber: string;
    district: string;
    experience: bigint;
    longitude?: number;
    village: string;
    mandal: string;
    phone: string;
    pincode: bigint;
}): Promise<{
    id: string;
    bio: string;
    latitude: [] | [number];
    name: string;
    profilePhoto: [] | [_ExternalBlob];
    isAvailable: boolean;
    registrationNumber: string;
    district: string;
    experience: bigint;
    longitude: [] | [number];
    village: string;
    mandal: string;
    phone: string;
    pincode: bigint;
}> {
    return {
        id: value.id,
        bio: value.bio,
        latitude: value.latitude ? candid_some(value.latitude) : candid_none(),
        name: value.name,
        profilePhoto: value.profilePhoto ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.profilePhoto)) : candid_none(),
        isAvailable: value.isAvailable,
        registrationNumber: value.registrationNumber,
        district: value.district,
        experience: value.experience,
        longitude: value.longitude ? candid_some(value.longitude) : candid_none(),
        village: value.village,
        mandal: value.mandal,
        phone: value.phone,
        pincode: value.pincode
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
